### ISSUE TITLE
Runtime error on old android versions

### ISSUE THREAD

**Issue by giregk** [convertigo/c8osdk-js#2]
AndroidRuntime  E  FATAL EXCEPTION: mqt_native_modules
                         E  Process: tech.bam.edailycheck.staging, PID: 11295
                         E  java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
                         E      at com.convertigo.reactnative.RCTC8oSDK.init(RCTC8oSDK.java:63)
                         E      at java.lang.reflect.Method.invokeNative(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:515)
                         E      at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:
                            372)
                         E      at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:
                            160)
                         E      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                         E      at android.os.Handler.handleCallback(Handler.java:733)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(
                            MessageQueueThreadHandler.java:29)
                         E      at android.os.Looper.loop(Looper.java:136)
                         E      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueT
                            hreadImpl.java:192)
                         E      at java.lang.Thread.run(Thread.java:841)

**Comment by giregk** [comment]
wrong repo
